nodeLinker: node-modules

enableGlobalCache: false

npmRegistryServer: "https://registry.npmjs.org"

npmAlwaysAuth: true

logFilters:
  - code: YN0013
    level: discard

compressionLevel: mixed

enableMirror: false